# -*- coding: utf-8 -*-
"""App_Projeto_IoT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_fi9dXz_li3B9RnWF4gpYLkH2zqWMKy
"""

import socket
import argparse

temperaturas=[]
leituras = []
quant = 20


HOST = "159.203.79.141"
PORT = 50000
device_id = "id_device"

# Create a socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect to the remote host and port
sock.connect((HOST, PORT))

print("conectado")

# Send a request to the host
sock.send("app\n".encode()[:-1])

# Get the host's response, no more than, say, 1,024 bytes
response_data = sock.recv(1024)

sresponse = response_data.decode("utf-8")
print(sresponse)

if(sresponse == "fail"):
  sock.close()
  exit()

# Send a request to the host
sock.send((device_id+"\n").encode()[:-1])

# Get the host's response, no more than, say, 1,024 bytes
response_data = sock.recv(1024)

sresponse = response_data.decode("utf-8")
print(sresponse)

if(sresponse == "fail"):
  sock.close()
  exit()

for i in range (quant):
  # Get the host's response, no more than, say, 1,024 bytes
  response_data = sock.recv(1024).decode("utf-8")

  print(f"Dado recebido: {response_data}")

  temperaturas.append(float(response_data))
  leituras.append(i+1)

# Terminate
sock.close( )
print("\n")
print("----------------")
print("\n")
print("Temperaturas recebidas:")
print(temperaturas)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

#Gráfico Linha

dados = {
    'N° de leituras' : leituras,
    'Temperaturas': temperaturas
}

df = pd.DataFrame(dados)
print(df)
plt.figure(figsize=(8,6))
plt.xticks(rotation=45)
sns.set_theme(style="darkgrid")
sns.lineplot(data=df, x='N° de leituras', y='Temperaturas', color='blue')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

#Gráfico Linha

dados = {
    'Dia de leitura' : [1]*quant,
    'Temperaturas': temperaturas
  }

df = pd.DataFrame(dados)
print(df)
sns.catplot(data=df, x="Dia de leitura", y="Temperaturas", kind="box")
