# -*- coding: utf-8 -*-
"""App_Atividade2_IoT_Ciclo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GySUEp2yVquks3d_pWgp-JzpuyGmA87
"""

pip install paho-mqtt

import paho.mqtt.client as mqtt

lista = []

def on_subscribe(client, userdata, mid, reason_code_list, properties):
    # Since we subscribed only for a single channel, reason_code_list contains
    # a single entry
    if reason_code_list[0].is_failure:
        print(f"Broker rejected you subscription: {reason_code_list[0]}")
    else:
        print(f"Broker granted the following QoS: {reason_code_list[0].value}")

def on_unsubscribe(client, userdata, mid, reason_code_list, properties):
    # Be careful, the reason_code_list is only present in MQTTv5.
    # In MQTTv3 it will always be empty
    if len(reason_code_list) == 0 or not reason_code_list[0].is_failure:
        print("unsubscribe succeeded (if SUBACK is received in MQTTv3 it success)")
    else:
        print(f"Broker replied with failure: {reason_code_list[0]}")
    client.disconnect()

def on_message(client, userdata, message):
    print(message.payload)
    lista.append(float(message.payload))
    print(lista)
    #Relaização de 5 leituras para teste
    if len(lista) >= 5:
        client.unsubscribe("$SYS/#")


def on_connect(client, userdata, flags, reason_code, properties):
    if reason_code.is_failure:
        print(f"Failed to connect: {reason_code}. loop_forever() will retry connection")
    else:
        # we should always subscribe from on_connect callback to be sure
        # our subscribed is persisted across reconnections.
        client.subscribe("topic/exemplo/matheussilva")

mqttc = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
mqttc.on_connect = on_connect
mqttc.on_message = on_message
mqttc.on_subscribe = on_subscribe
mqttc.on_unsubscribe = on_unsubscribe

mqttc.connect("test.mosquitto.org", 1883)
mqttc.loop_forever()